### ISSUE TITLE
Problem in documentation

### ISSUE THREAD

**Issue by Huascar321** [botika/prisma-generator-nestjs-dto#204]
Hi Botika, thanks for keeping this project going, I really appreciate what you do here.

There is a problem in the documentation provided by "https://prisma-generator-nestjs.netlify.app/"

In the configuration file within the prisma schema you put:

`fileNamingStyle                 = "kebak"`

This is incorrect and will generate an error when using the npx prisma generate command:

**'kebak' is not a valid file naming style. Valid options are 'kebab', 'camel', 'pascal', 'snake'.**

The correct term should be "kebab"

**Comment by botika** [comment]
P
