### ISSUE TITLE
class-trasformer @Type support for nested objects

### ISSUE THREAD

**Issue by AliYusuf95** [botika/prisma-generator-nestjs-dto#213]
Hi, thank you for maintaining this lib.
I use Prisma with mongodb and I'm utilizing [Composite types](https://www.prisma.io/docs/concepts/components/prisma-client/composite-types).
It would be wonderful if you can add support to `@Type` since to [validate nested object](https://github.com/typestack/class-validator#validating-nested-objects), it must be an instance of a class otherwise validation will not work.

**Comment by botika** [comment]
You say that? https://github.com/botika/prisma-generator-nestjs-dto/blob/692e19cb3da2021a373145ed25d412b67c8b2ef9/test/__snapshots__/class-validator.test.ts.snap#L116-L118

**Comment by AliYusuf95** [comment]
Yes, `@ValidateNested()` will not work unless the field is class instance. Which can't be done as far I know without class-trasformer 
 `@Type` annotation.

**Comment by botika** [comment]
https://github.com/botika/prisma-generator-nestjs-dto/releases/tag/1.14.4  fixed. Thanks!
