### ISSUE TITLE
[question] How to use/install with npm

### ISSUE THREAD

**Issue by ao-alex** [botika/prisma-generator-nestjs-dto#223]
Hi, thanks for maintaining these lib and adding new features !
 A silly question how to use this lib. I have  tried to install with 
`npm install https://github.com/botika/prisma-generator-nestjs-dto`
`npm install --save-dev git+https://github.com/botika/prisma-generator-nestjs-dto.git`  
`"postinstall": "cd ./node_modules/prisma-generator-nestjs && npm install && npm run build"`
but  in all cases in the node_modules I see only readme, package.json and license files, no actual code.
Is there a specific way to install it?

Here is my package.json `
{ 
 "prisma-generator-nestjs": "https://github.com/botika/prisma-generator-nestjs-dto.git",
}
`

**Comment by AliYusuf95** [comment]
use the following:
`npm -D prisma-generator-nestjs`
it's in the [documentation](https://prisma-generator-nestjs.netlify.app/quick-start.html)

**Comment by botika** [comment]
`npm i -D prisma-generator-nestjs`

https://www.npmjs.com/package/prisma-generator-nestjs
